#!/bin/bash
cd "$( dirname "$0" )"
sys=$(uname);
if [[ sys == "Linux" && -f /etc/lsb-release ]]
then
	chmod +x MCNotifier
	echo "Place the files into your Minecraft Server root directory (containing server.log) and run MCNotifier!"
	exit
fi
sysversion=$(sw_vers -productVersion);
if [[ ! "$sysversion" == *"10.8"* ]] # Check if OS X version is less than 10.8
then
	echo "Mountain Lion is required for MCNotifier to work as it uses Notification Center to deliver information, Please consider upgrading to Mountain Lion or try it on another Mac."
	exit
fi
if [[ ! -f /usr/bin/xcodebuild ]]
then
	echo "MCNotifier requires that you have Xcode installed, this is required to build certain dependencies for it to run correctly."
	echo "Please download it from the Mac App Store or the Apple Developer Portal"
	exit
fi
if [[ -d terminal-notifier.app ]]
then
	rm -R terminal-notifier.app
fi
echo "** Cloning terminal-notifier..."
git clone git://github.com/alloy/terminal-notifier.git 
cd terminal-notifier
echo "** Building terminal-notifier..."
xcodebuild CODE_SIGN_IDENTITY="" BUILD_DIR="./" > /dev/null
echo "** Built terminal-notifier!"
cp -R Release/terminal-notifier.app ../terminal-notifier.app
cd ../
sudo rm -R terminal-notifier
chmod +x MCNotifier
echo "Place the files into your Minecraft Server root directory (containing server.log) and run MCNotifier!"