#!/bin/bash
cd "$( dirname "$0" )"
if [[ ! -f /usr/bin/xcodebuild ]]
then
	echo "MCNotifier requires that you have Xcode installed, this is required to build certain dependencies for it to run correctly."
	echo "Please download it from the Mac App Store or the Apple Developer Portal"
	exit
fi
if [[ -d terminal-notifier.app ]]
then
	rm -R terminal-notifier.app
fi
echo "** Cloning terminal-notifier..."
git clone git://github.com/alloy/terminal-notifier.git 
cd terminal-notifier
echo "** Building terminal-notifier..."
xcodebuild CODE_SIGN_IDENTITY="" BUILD_DIR="./" > /dev/null
echo "** Built terminal-notifier!"
cp -R Release/terminal-notifier.app ../terminal-notifier.app
cd ../
sudo rm -R terminal-notifier
chmod +x MCNotifier
echo "Place the files into your Minecraft Server root directory (containing server.log) and run MCNotifier!"